---

- name: remove temporary build directory
  file:
    path: "/tmp/build"
    state: absent
  tags: deploy-source
  
- name: remove temporary build directory
  file:
    path: "/tmp/build"
    state: directory
  tags: deploy-source    

- name: remove existing build directory
  file:
    path: "/home/syscon/system-controller"
    state: absent
  tags: deploy-source
  
- name: remove existing build directory
  file:
    path: "/home/syscon/system-controller"
    state: directory
  tags: deploy-source  
    
- name: Copy the code from repository
  git:
    repo: "{{ repository }}"
    dest: "/tmp/build"
    depth: 1
    #version: "{{ release_version }}"    
  tags: deploy-source

- name: move source into install location
  become: true
  become_method : sudo
  command: mv "/tmp/build/source" "/home/syscon/system-controller/source"
  tags: deploy-source  